Repository auth0/auth0-PHP, pull requests merged in 2018-10, with the labels that each got.

#298 Fix documentation for Auth0 constructor options
  src/Auth0.php
Labels: CH: Added

#297 Fix bad exception message generation
  src/JWTVerifier.php
  tests/API/Helpers/TokenTest.php
Labels: CH: Fixed

#300 Change telemetry headers to new format and add tests
  src/API/Authentication.php
  src/API/Helpers/ApiClient.php
  src/API/Helpers/InformationHeaders.php
  src/API/Oauth2Client.php
  src/Auth0.php
  src/Auth0Api.php
  src/Auth0AuthApi.php
  src/Auth0JWT.php
  tests/API/Helpers/InformationHeadersTest.php
Labels: CH: Changed
