Repository auth0/auth0-PHP, pull requests merged in 2019-12, with the labels that each got.

#375 Fix mkdir race condition in FileSystemCacheHandler
  src/Helpers/Cache/FileSystemCacheHandler.php
Labels: CH: Fixed

#402 Move AuthorizationBearer to new namespace
  src/API/Authentication.php
  src/API/Header/AuthorizationBearer.php
  src/API/Management.php
  tests/API/Header/HeaderTest.php
Labels: CH: Changed, tiny

#407 Add deprecation notices for removals in v7 major release
  src/API/Helpers/State/DummyStateHandler.php
  src/API/Helpers/State/SessionStateHandler.php
  src/API/Helpers/State/StateHandler.php
  src/Helpers/Cache/CacheHandler.php
  src/Helpers/Cache/FileSystemCacheHandler.php
  src/JWTVerifier.php
  src/Store/EmptyStore.php
  src/Store/SessionStore.php
Labels: CH: Deprecated, tiny

#406 Add default scopes to Auth0 class
  src/Auth0.php
  tests/Auth0Test.php
Labels: CH: Added, tiny

#405 fix: add missing options for renewTokens method
  src/Auth0.php
  tests/Auth0Test.php
Labels: CH: Added, tiny

#408 Release 5.7.0
  CHANGELOG.md
  src/API/Helpers/ApiClient.php
  tests/Auth0Test.php
Labels: tiny
