Repository auth0/auth0-PHP, pull requests merged in 2019-09, with the labels that each got.

#357 Fix boolean form parameters not sending as strings
  src/API/Helpers/RequestBuilder.php
  tests/API/Helpers/RequestBuilderTest.php
  tests/API/Management/ClientGrantsTest.php
  tests/API/Management/EmailTemplatesMockedTest.php
  tests/API/Management/EmailsMockedTest.php
Labels: CH: Fixed, small

#354 Add additional API params to Jobs > importUsers
  src/API/Management/Jobs.php
Labels: CH: Added

#362 Deprecate and stop using magic call method on ApiClient
  src/API/Helpers/ApiClient.php
  src/API/Management/Blacklists.php
  src/API/Management/ClientGrants.php
  src/API/Management/DeviceCredentials.php
  src/API/Management/Emails.php
  src/API/Management/Jobs.php
  src/API/Management/Stats.php
  src/API/Management/Tenants.php
  src/API/Management/Tickets.php
  src/API/Management/UserBlocks.php
  src/API/Management/UsersByEmail.php
  tests/API/Management/RolesMockedTest.php
  tests/API/Management/UsersMockedTest.php
Labels: CH: Deprecated, small

#361 Deprecate addPathVariable and dump methods on RequestBuilder
  src/API/Helpers/RequestBuilder.php
  src/API/Management/Roles.php
  src/API/Management/Users.php
Labels: CH: Deprecated, tiny

#360 Deprecate TokenGenerator class
  src/API/Authentication.php
  src/API/Helpers/TokenGenerator.php
  src/API/Management/Users.php
  src/API/Oauth2Client.php
  src/Auth0Api.php
  src/Auth0AuthApi.php
  src/Auth0JWT.php
Labels: CH: Deprecated, tiny

#364 Fix integration and add mock tests Blacklists
  tests/API/ApiTests.php
  tests/API/Management/BlacklistsTest.php
Labels: CH: Added, small

#374 Set content-type for DELETE method
  src/API/Helpers/ApiClient.php
  tests/API/Management/ConnectionsMockedTest.php
  tests/API/Management/UsersMockedTest.php
  tests/bootstrap.php
Labels: tiny

#373 Deprecated unused JWKFetcher methods
  src/Helpers/JWKFetcher.php
Labels: CH: Deprecated, tiny
