Repository auth0/auth0-PHP, pull requests merged in 2020-08, with the labels that each got.

#439 Throw InvalidTokenException instead of RuntimeException when parsing malformed token (fix #438)
  src/Helpers/Tokens/SignatureVerifier.php
  tests/Helpers/Tokens/AsymmetricVerifierTest.php
Labels: CH: Changed

#443 Update composer requirements to support guzzle ~7.0
  composer.json
Labels: CH: Added

#448 Run integration tests on master branch
  .circleci/config.yml
Labels: small

#451 Add Support for Log Streams Management APIs
  src/API/Management.php
  src/API/Management/LogStreams.php
  tests/unit/API/Management/LogStreamsTest.php
Labels: CH: Added, medium

#452 Release 7.3.0
  CHANGELOG.md
  src/API/Helpers/ApiClient.php
Labels: tiny
