Repository auth0/auth0-PHP, pull requests merged in 2021-04, with the labels that each got.

#483 [SDK-2435] Add Organizations support to Management API Client
  phpunit.xml.dist
  src/API/Management.php
  src/API/Management/GenericResource.php
  src/API/Management/Jobs.php
  src/API/Management/Organizations.php
  src/API/Management/Tickets.php
  src/API/Management/Users.php
  src/Auth0.php
  tests/integration/API/Management/OrganizationsIntegrationTest.php
  tests/unit/API/Management/OrganizationsTest.php
  tests/unit/API/Management/UsersMockedTest.php
Labels: CH: Added, review:small

#485 Release 7.8.0
  CHANGELOG.md
  src/API/Helpers/ApiClient.php
Labels: review:tiny

#488 [SDK-2456] Remove Organizations Beta Labelling
  README.md
Labels: review:tiny

#491 [SDK-2464] Add guidance for org validation
  README.md
Labels: review:tiny

#490 [SDK-2486] Allow overriding 0.2 delay in integration testing API requests
  tests/API/ApiTests.php
  tests/bootstrap.php
  tests/integration/API/Management/BlacklistsIntegrationTest.php
  tests/integration/API/Management/ClientGrantsIntegrationTest.php
  tests/integration/API/Management/ClientsIntegrationTest.php
  tests/integration/API/Management/JobsIntegrationTest.php
  tests/integration/API/Management/LogsIntegrationTest.php
  tests/integration/API/Management/OrganizationsIntegrationTest.php
  tests/integration/API/Management/ResourceServersIntegrationTest.php
  tests/integration/API/Management/RulesIntegrationTest.php
Labels: review:tiny

#489 Add support for guzzle ^6.0 (or ^7.0)
  composer.json
Labels: CH: Changed, dependencies
