Repository auth0/auth0-PHP, pull requests merged in 2022-04, with the labels that each got.

#613 Update `firebase/php-jwt` dependency to 6.0
  composer.json
Labels: dependencies

#614 throw InvalidTokenException on JsonException
  src/Exception/InvalidTokenException.php
  src/Token/Parser.php
  tests/Unit/Token/ParserTest.php
Labels: CH: Changed

#619 [SDK-3267] Add configuration strategy constants
  src/Configuration/SdkConfiguration.php
Labels: CH: Added, review:tiny

#620 [SDK-3268] Add bearer token extraction helper
  src/Auth0.php
  tests/Unit/Auth0Test.php
  tests/Utilities/TokenGenerator.php
Labels: CH: Added, review:small

#626 Release 8.2.0
  CHANGELOG.md
  src/Auth0.php
Labels: review:tiny
