Repository auth0/auth0-PHP, pull requests merged in 2022-11, with the labels that each got.

#669 fix: Remove redundant Cache `getItem()` call in `Auth0\SDK\Token\Verifier::getKeySet()`
  src/Token/Verifier.php
Labels: CH: Fixed

#672 Release 8.3.7
  CHANGELOG.md
  src/Auth0.php
Labels: review:tiny

#674 fix: Always store provided `state` in transient medium
  .github/workflows/checks.yml
  composer.json
  src/API/Authentication.php
  src/API/Management.php
  src/API/Management/ManagementEndpoint.php
  src/Auth0.php
  src/Contract/TokenInterface.php
  src/Event/HttpRequestBuilt.php
  src/Event/HttpResponseReceived.php
  src/Event/Psr14Store/Boot.php
  src/Event/Psr14Store/Clear.php
  src/Event/Psr14Store/Defer.php
  src/Event/Psr14Store/Delete.php
  src/Event/Psr14Store/Destruct.php
  src/Event/Psr14Store/Get.php
  src/Event/Psr14Store/Set.php
  src/Store/CookieStore.php
  src/Store/Psr14Store.php
  src/Store/Psr6Store.php
  src/Store/SessionStore.php
  src/Token.php
  src/Token/Parser.php
  src/Token/Validator.php
  src/Token/Verifier.php
  src/Utility/EventDispatcher.php
  src/Utility/HttpClient.php
  src/Utility/HttpRequest.php
  src/Utility/HttpResponsePaginator.php
  src/Utility/Request/FilteredRequest.php
  src/Utility/Request/PaginatedRequest.php
  src/Utility/Request/RequestOptions.php
  src/Utility/Toolkit/Assert.php
  src/Utility/Toolkit/Filter.php
  src/Utility/Toolkit/Filter/ArrayFilter.php
  src/Utility/Toolkit/Filter/StringFilter.php
  src/Utility/TransientStoreHandler.php
  tests/Unit/API/AuthenticationTest.php
  tests/Unit/API/ManagementTest.php
  tests/Unit/Configuration/SdkConfigurationTest.php
  tests/Unit/Store/SessionStoreTest.php
  tests/Unit/Token/ParserTest.php
  tests/Unit/Token/VerifierTest.php
  tests/Utilities/TokenGenerator.php
Labels: CH: Fixed, review:small
