Repository auth0/auth0-PHP, pull requests merged in 2022-02, with the labels that each got.

#595 Improve readme to reflect v8.0 documentation chapters
  README.md
  src/Utility/PKCE.php
  src/Utility/TransientStoreHandler.php
Labels: documentation

#597 [SDK-3117] Add Attack Protection endpoints
  src/API/Management.php
  src/API/Management/AttackProtection.php
  src/Contract/API/Management/AttackProtectionInterface.php
  tests/Unit/API/Management/AttackProtectionTest.php
Labels: CH: Added, review:small

#598 Release 8.1.0
  CHANGELOG.md
  src/Auth0.php
Labels: review:tiny
